version: '3'
services:
  payara:
    build: ../images/payara
    environment:
     - ADMIN_PASSWORD=adminadmin
    ports:
     - "8080:8080"
     - "4848:4848"
  wildfly:
    build: ../images/wildfly
    ports:
     - "9090:8080"
     - "9990:9990"
  tomee:
    build: ../images/tomee
    ports:
     - "7070:8080"